config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :accounts do
    member do
      get 'user_list'
      get 'income_list'
      get 'expense_list'
      get 'details'
    end
   resources :users
   resources :incomes
   resources :expenses
   resources :bingos
   resources :advanced_search
  end

end

app/models/bingo.rb
class Bingo < ActiveRecord::Base
	belongs_to :account
	validates :firstname,:presence => :true
	validates_format_of :firstname,:with => /[A-Za-z]/,:if => Proc.new{|bingo| bingo.firstname.present?}
	validates :amount,:presence => true,:numericality => {:allow_blank => true}

	def self.search(firstname)
		if firstname.present?
			self.where('firstname LIKE ?',"%#{firstname}%")
		else
			Bingo.all
		end
	end
end

app/controllers/bingos_controller.rb
class BingosController < ApplicationController
	def index
		@account = Account.find(params[:account_id])
		@bingos = Bingo.search(params[:firstname])
	end

	def new
		@account = Account.find(params[:account_id])
		@bingo = Bingo.new
	end

	def create
		@account = Account.find(params[:account_id])
		@bingo = Bingo.create(bingo_params)
		if @bingo.save
			redirect_to account_bingos_path
		else
			render action: :new
		end

	end

	def edit
		@account = Account.find(params[:account_id])
		@bingo = Bingo.find(params[:id])
	end

	def update
		@bingo = Bingo.find(params[:id])
		if @bingo.update_attributes(bingo_params)
			redirect_to account_bingos_path
		else
			render action: :new
		end
	end

	def destroy
		@bingo = Bingo.find(params[:id])
		
		@bingo.destroy
		redirect_to account_bingos_path

	end

	private
	def bingo_params
		params.require(:bingo).permit(:firstname,:lastname,:gender,:amount,:date,:account_id)
	end
end

app/helpers/bingos_helper.rb
module BingosHelper
end

app/views/bingos/edit.html.erb
<%= form_for [@account,@bingo] do |f|%>
	<div>
		<%= f.label :firstname %> :
		<%= f.text_field :firstname %>
	</div>

	<div>
		<%= f.label :lastname %> :
		<%= f.text_field :lastname%>
	</div>

	<div>
		<%= f.label :gender %>
		<%= f.radio_button(:gender,"male") %> :Male
		<%= f.radio_button(:gender,"female") %> :Female
	</div>

	<div>
		<%= f.label :amount%> :
		<%= f.text_field :amount%>
	</div>

	<div>
		<%= f.label :date %>
		<%= f.date_field :date %>
	</div>

	<div>
		<%= f.submit %>
	</div>
<% end %>

app/views/bingos/index.html.erb
<!DOCTYPE html>
<html>
	<head>
		<style>
			body { background-color: #FFFFCC; font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
			    width: 100%;}

		</style>
	</head>
			<%= form_tag account_bingos_path,:method => 'get' do %>
				Name : <%= text_field_tag :firstname,params[:firstname] %><br>
				<%= submit_tag "Search" %>
				<%= link_to 'clear',params.clear %>
			<% end %>

			<strong><h3>List of Bingo holders of <%= @account.name %></h3></strong>	


	<body>
		<table bgcolor="#FFFFFF" border="2" cellspacing="1" cellpadding="1">
				
			<thead>
				<tr>
					<th>Name</th>
					<th>Amount</th>
					
			</thead>
				

			<tbody>
					<% for bingo in @bingos%>
				<tr>
					<td><%= bingo.firstname %></td>
					<td><%= bingo.amount%><br></td>
					<td><%= link_to 'Edit',edit_account_bingo_path(@account,bingo) %></td>
					<td><%= link_to 'Delete',account_bingo_path(@account,bingo),
					         method: :delete,data: {confirm: 'Are you sure?'}%></td>
				</tr>
					<% end %>
			</tbody>
		</table><br>
	</body>
</html>
				



<%= link_to 'click here for complete details of account holders',details_account_path(@account,bingo) %><br>
<%= link_to 'Create new bingo',new_account_bingo_path(@account,bingo)%>

app/views/bingos/new.html.erb
<html>
	<style>
			body{
				background-color: hsla(120,100%,75%,0.3);background-position: right top;
				 	font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
				    width: 100%;
			}
	</style>

	<%= form_for [@account,@bingo] do |f|%>
		<% if @bingo.errors.any? %>
			<div id="Error_messages">
				<ol>
					<%= pluralize(@bingo.errors.count,"error") %> prohibited bingo from being saved:
					<% for error in @bingo.errors.full_messages %>
					 <li><%= error %></li>
				    <% end %>
			    </ol>
			</div>
		<% end %>
				

		<div class="input-box">
			<%= f.label :firstname %>
			<%= f.text_field :firstname %>
		</div>

		<div class="input-box">
			<%= f.label :lastname %>
			<%= f.text_field :lastname%>
		</div>

		<div class="input-box">
			<%= f.label :gender %>
			<%= f.radio_button(:gender,"male") %> :Male
			<%= f.radio_button(:gender,"female") %> :Female
		</div>

		<div class="input-box">
			<%= f.label :amount%>
			<%= f.text_field :amount%>
		</div>

		<div class="input-box">
			<%= f.label :date %>
			<%= f.date_field :date %>
		</div>

		<div class="input-box">
			<%= f.submit %>
		</div>
	<% end %>

</html>