config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :accounts do
    member do
      get 'user_list'
      get 'income_list'
      get 'expense_list'
      get 'details'
    end
   resources :users
   resources :incomes
   resources :expenses
   resources :bingos
   resources :advanced_search
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :account
  has_one :bingo
  validates_format_of(:firstname,{:with => /[A-Za-z]/,:if => Proc.new{|user| user.firstname.present?}})
  validates(:firstname, :place, :presence => true)
  validates_format_of :place,{:with => /[A-Za-z]/,:if => Proc.new{|user| user.place.present?}}


  def self.search(first_name, place)
  	conditions = []

  	if first_name.present?
  		conditions << "firstname LIKE '%#{first_name}%'"
  	end

  	if place.present?
  		conditions << "place LIKE '%#{place}%'"
  	end

  	query = User.order("firstname")
  	query = query.where( conditions.join(" AND ") ) if conditions.size > 0
  	query.all

  	#self.where('firstname Like ? or place Like ?',"%#{search}%", "%#{search}%")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@account = Account.find(params[:account_id])
		@user = User.new
	end

	def index
		# puts "****** "
		# p params
		# puts "****** "
		# puts params[:firstname]
		# puts "****** "
		# puts params[:place]
		# puts "****** "

		@account = Account.find(params[:account_id])
		@users = User.search(params[:firstname],params[:place])# equal to select * from users where firstname = ""place = "",order by firstname as it is used in model
		
	end

	def create
		@account = Account.find(params[:account_id])
		@user = User.create(user_params.merge({"account_id" => params[:account_id]}))
		if @user.save
			redirect_to account_users_path
		else
			render action: :new 
		end
	end

	def edit
		@account = Account.find(params[:account_id])
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to account_users_path
		else
			render action: :edit
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to account_users_path																		
	end

	private
	def user_params
		params.require(:user).permit(:firstname,:lastname,:gender,:place)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= form_for [@account,@user] do |f| %>
	<div>
	<%= f.label :firstname %> :
	<%= f.text_field :firstname %><br>
	</div>

	<div>
	<%= f.label :lastname %> :
	<%= f.text_field :lastname %><br>
	</div>

	<div>
		<%= f.label :gender%>:
		<%= f.radio_button(:gender,"female")  %> male
		<%= f.radio_button(:gender, "female") %> female
	</div>

	<div>
		<%= f.label :place %>:
		<%= f.text_field :place %>
	</div>	

	<div>
	<%= f.submit %>
	</div>

<% end %>

app/views/users/index.html.erb
<html>
	<style>
	body {font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
			    width: 100%;}
	</style>
	<%= form_tag account_users_path,:method => 'get' do %>
		<p>
			Name: <%= text_field_tag :firstname,params[:firstname] %><br>
			Place: <%= text_field_tag :place,params[:place]  %><br>
			<%= submit_tag :Search %>
			<%= link_to 'clear',params.clear %>
		</p>
	<% end %>


		<h2><strong>Users of <%= @account.name %></strong></h2>
	<table border="2" cellspacing="0" cellpadding="2">
		<thead>
			<tr>

			 	<td>First Name</td>
			 	<td>Last Name</td>
			 	<td>Gender</td>
			 	<td>Place</td>
			 	<td>Edit</td>
			 	<td>Delete</td>
		 	</tr>
	 	</thead>

	 	<tbody>
				<% for user in @users %>
		 	<tr>
				<td><%= user.firstname %></td>
				<td><%= user.lastname %></td>
				<td><%= user.gender %></td>
				<td><%= user.place %></td>
				<td><%= link_to 'edit',edit_account_user_path(@account,user)%></td>	
				<td><%= link_to 'delete',account_user_path(@account,user), 
				      method: :delete,data: {confirm: 'Are you sure?'}%></td>
			</tr>
				<% end %>
		</tbody>

	</table>
</html>
<%= link_to 'create new user',new_account_user_path(@account,user)%>

app/views/users/new.html.erb
<h2>Fill the form to register</h2>

<%= form_for [@account,@user]  do |f| %>
	<% if @user.errors.any? %>
		<div id="Error_messages">
			<ol>
			<%= @user.errors.size %> <%= (@user.errors.size > 1) ? "Errors" : "Error"%> 
				<% for error in @user.errors.full_messages %>
					<li><%= error %></li>
				<% end %>
			</ol>
		</div>		
	<% end %>

	<div class="input-box">
		<%= f.label :firstname %> 
		<%= f.text_field :firstname %>
	</div>

	<div class="input-box">
		<%= f.label :lastname %> 
		<%= f.text_field :lastname %>
	</div>

	<div class="input-box">
		<%= f.label :gender%>
		<%= f.radio_button(:gender,"male")  %> male
		<%= f.radio_button(:gender, "female") %> female 
	</div>

	<div class="input-box">
		<%= f.label :place %>
		<%= f.text_field :place %>
	</div>

	<div class="input-box">
	<%= f.submit %>
	</div>

<% end %>