config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :accounts do
    member do
      get 'user_list'
      get 'income_list'
      get 'expense_list'
      get 'details'
    end
   resources :users
   resources :incomes
   resources :expenses
   resources :bingos
   resources :advanced_search
  end

end

app/models/income.rb
class Income < ActiveRecord::Base
	belongs_to :account
	validates :name, :presence => true
	validates_format_of(:name,{:with => /[A-Za-z]/,:if => Proc.new{|income| income.name.present?}})
	validates :amount,{:presence => true, :numericality => {:allow_blank => true} }


	def self.search(name,amount)
		conditions = []
		if name.present?
			conditions << "name LIKE '%#{name}%'"
	 	end
	 	if amount.present?
	 		conditions << "amount LIKE '%#{amount}%'"
	 	end

	 	query = Income.order("name")
	 	query = query.where(conditions.join(" AND ")) if conditions.size > 0
	 	query.all

	end 
end	

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
	def index
		@account = Account.find(params[:account_id])
		@incomes = Income.search(params[:name],params[:amount])
		@total = Income.sum(:amount)
	end

	def new
		@account = Account.find(params[:account_id])
		@income = Income.new
	end

	def create
		@account = Account.find(params[:account_id])
        @income = Income.create(income_params.merge({"account_id" => params[:account_id]}))
        if @income.save
           redirect_to account_incomes_path
        else 
        	render action: :new
        end
	end

	def edit
		@account = Account.find(params[:account_id])
		@income = Income.find(params[:id])
	end
	def show
		@account = Account.find(params[:account_id])
		@income = Income.find(params[:id])
	end

	def update
		@income = Income.find(params[:id])
		if @income.update_attributes(income_params)
			redirect_to account_incomes_path
		else
			render action: :new
		end

	end



	def destroy
		@income = Income.find(params[:id])
		@income.destroy
		redirect_to account_incomes_path
	end

	private
	def income_params
		params.require(:income).permit(:name,:amount,:purpose,:account_id)
	end
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/incomes/edit.html.erb
<%= form_for [@account,@income] do |f|%>
	<div>
	<%= f.label :name %> :
	<%= f.text_field :name %><br>
	</div>

	<div>
	<%= f.label :amount %> :
	<%= f.text_field :amount %><br>
	</div>

	<div>
	<%= f.label :purpose %> :
	<%= f.text_area :purpose %><br>
	</div>

	<div>
	<%= f.submit%>
	</div>
	
<% end%>

app/views/incomes/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<style>
	body {background-color: rgba(0,255,0,0.3);}
	</style>
</head>
<body>	
		<div class="hidden">
			<form>
				<fieldset >
						<legend><h4>Search Form</h4></legend>
					
							<%= form_tag account_incomes_path,:method => 'get' do %>
								<div class="input-box">
									<%= label_tag :name %>
									<%= text_field_tag :name,params[:name] %>
								</div>

								<div class="input-box">
									<%= label_tag :amount %>
									<%= text_field_tag :amount,params[:amount] %>
								</div>

								<div class="input-box">
									<%= submit_tag :Search %>
									<%= link_to 'clear',params.clear %>
								</div>
							<% end %>
				</fieldset>
			</form>
		</div>
	<h3>List Of Incomes</h3>

	<table bgcolor="white" border="2" cellspacing="0" cellpadding="3">
		<thead>
			<tr>
				<th>Name</th>
				<th>Amount</th>
				<th>Description</th>
				<th>Account_id</th>
				<th>Edit</th>
				<th>Destroy</th>
			</tr>
		</thead>
		<tbody>
				<% for income in @incomes %>
			<tr>
				<td><%= income.name %></td>
				<td><%= income.amount %></td>
				<td><%= income.purpose %></td>
				<td><%= income.account_id %></td>
				<td><%= link_to 'Edit',edit_account_income_path(@account,income) %></td>
				<td><%= link_to 'Delete',account_income_path(@account,income),
						method: :delete,data: {confirm: 'Are you sure?'} %></td>
			</tr>
				<% end %>		

		</tbody>

	</table><br>
</body>
</html>
				<strong><td>Total Income <%= @total%></td></strong><br>
<%= link_to 'Enter new income', new_account_income_path(@account,income) %>

app/views/incomes/new.html.erb
<html>
	<thead>
		<style>
			body { background-color:  linen;}
		</style>
	</thead>

	<%= form_for [@account,@income] do |f|%>
		<% if @income.errors.any? %>
			<div id="Error_messages"> 
				<ol>
					<%= pluralize(@income.errors.count,"error") %> prohibited this income from being saved.

					<% for error in @income.errors.full_messages %>
						<li><%= error %></li>
					<% end %>
				</ol>
			</div>
		<% end %>
			
		<div class = "input-box">
			<%= f.label :name %> 
			<%= f.text_field :name %>
		</div>

		<div class = "input-box">
			<%= f.label :amount %> 
			<%= f.text_field :amount %>
		</div>

		<div class = "input-box">
			<%= f.label :purpose %> 
			<%= f.text_area :purpose %>
		</div>

		<div class = "input-box">
			<%= f.submit%>
		</div>
		
	<% end%>

</html>

app/views/incomes/show.html.erb
<table bgcolor="white" border="2" cellspacing="0" cellpadding="3">
		<thead>
			<tr>
				<td>Name</td>
				<td>Amount</td>
				<td>Purpose</td>
				<td>Account_id</td>
				<td>Edit</td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><%= @income.name %></td>
				<td><%= @income.amount%></td>
				<td><%= @income.purpose%></td>
				<td><%= @income.account_id%></td>
				<td><%= link_to 'edit',edit_account_income_path(@account,@income) %></td>

			</tr>
		</tbody>