config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :accounts do
    member do
      get 'user_list'
      get 'income_list'
      get 'expense_list'
      get 'details'
    end
   resources :users
   resources :incomes
   resources :expenses
   resources :bingos
   resources :advanced_search
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
	has_many :users
	has_many :incomes
	has_many :expenses
	has_one :bingo, through: :users
	validates(:name, :presence => true)#validates is a method with symbol name and hash as two parameters.
	validates_format_of(:name,
		{
			:with => /[A-Za-z]/,# value is a // regular exprssion
			:if => Proc.new {|account| account.name.present?}# value is a block-Proc.new is the way to create a block{}
		})
	validates :registration_number,	 
		{
			:presence => "true",
			:numericality => {:allow_blank => true}
		}

		def self.search(search)
			if search
				self.where('name LIKE?',"%#{search}%")
			else
				self.all
			end
			
		end
end
	



	 

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	http_basic_authenticate_with name: "vinu",password: "nithya",
	except: [:index,:show]
	def new
		@account = Account.new
	end

	def create
		@account = Account.create(account_params)
		if @account.save
			redirect_to accounts_path
		else
			render action: :new
		end
	end

	def user_list
		@account = Account.find(params[:id])
		@users = @account.users
	end

	def index
		if params[:search]
			@accounts = Account.search(params[:search])
		else
			@accounts = Account.all
		end

	end

	def details
		@account = Account.find(params[:id])
		@bingos = Bingo.all
	end
	

	def expense_list
		@account = Account.find(params[:id])
		@expenses = Expense.all
	end

	def income_list
		@account = Account.find(params[:id])
		@incomes = Income.all
	end

	def update
		@account = Account.find(params[:id])
		if @account.update_attributes(account_params)
			redirect_to accounts_path
		else
			render action: :new
		end
	end

	

	def edit
		@account = Account.find(params[:id])
	end

	def show
		@account = Account.find(params[:id])
		@total_income = Income.sum(:amount)
		@total_expense = Expense.sum(:amount)
		@balance = @total_income-@total_expense
	end

	def destroy
		@account = Account.find(params[:id])
		@account.destroy
		redirect_to accounts_path
		
	end

	private
	def account_params
		params.require(:account).permit(:name,:description,:place,:registration_number,:user_name)
	end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/details.html.erb
<!DOCTYPE html>
<html>
	<head>
		<style>
		 	body {background-color: hsla(120,100%,50%,0.3); font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
			    width: 100%; }
		</style>
	</head>
										
			<strong><h3>List of Bingo holders of <%= @account.name %></h3></strong>
	<body>
		<table border="2" bgcolor="#FFFFFF" cellpadding="1" cellspacing="1">
			<thead>
				<tr>
					<td>First Name</td>
					<td>Last Name</td>
					<td>Gender</td>
					<td>Amount</td>
				</tr>
			</thead>


			<tbody>
				<% for bingo in @bingos %>
					<tr>
						<td><%= bingo.firstname %><br></td>
						<td><%= bingo.lastname %><br></td>
						<td><%= bingo.gender %><br></td>
						<td><%= bingo.amount %><br></td>
					</tr>
				<% end %>
				
			</tbody>
		</table>
	</body>
</html>

<%= link_to 'Create new bingo',new_account_bingo_path(@account,bingo)%><br>
<%= link_to 'Back to bingo holders list',account_bingos_path(@account,bingo) %>

app/views/accounts/edit.html.erb
<!DOCTYPE html>
<html>
	<head>
		<style>
			 body { background-color: hsla(120,100%,75%,0.3);background-image:url("img_tharavadu2.jpg") ;background-position: right top;}
			 h2 {colour: orange;}
		</style>
	</head>
	<body>
		<h2>Register the details</h2>
		<%= form_for @account do |f|%>
			<div>
				<%= f.label :name, {:style => "width:100px; float:left "} %>
				<%= f.text_field :name %>
			</div>
			
			<div>	
				<%= f.label "description",{:style => "width:100px; float:left"} %>
				<%= f.text_area :description %>
			</div>
			
			<div>	
				<%= f.label :place, {:style => "width:100px; float:left"} %>
				<%= f.text_field :place %>
			</div>
			
			<div>	
				<%= f.label :registration_number,{:style => "width:100px; float:left"} %>
				<%= f.text_field :registration_number %><br><br>
			</div>
			
			<div>
				<%= f.label :user_name,{:style => "width:100px; float:left"} %>
				<%= f.text_field :user_name %>
			</div>	

			<div>
			<span style = "width:100px; float:left">&nbsp</span>
				<%= f.submit %>
			</div>	
		<% end %>
	</body>


</html>

app/views/accounts/expense_list.html.erb
<!DOCTYPE html>
<html>
	<head>
		<style>
			body{ background-color:#D8D8D8; }
		</style>
	</head>
	<body>
		<table bgcolor="white" border="1" cellpadding="2" cellspacing="0">
			<thead>
				<tr>
					<td>Amount</td>
					<td>Purpose</td>
					<td>Account Id</td>
					<td>Edit</td>
					<td>Destroy</td>
				</tr>
			</thead>
			<tbody>
					<% for expense in @expenses %>
				<tr>
						<td><%= expense.amount %></td>
						<td><%= expense.purpose %></td>
						<td><%= expense.account_id %></td>
						<td><%= link_to 'edit',edit_account_expense_path(@account,expense)%></td>
						<td><%= link_to 'delete',account_expense_path(@account,expense),
								method: :delete,data: {confirm: 'Are you sure?'} %></td>
				</tr>
					<% end %>
			</tbody>
		</table>
	</body>
</html>
<%= link_to 'Create new expense',new_account_expense_path(@account,expense) %>

app/views/accounts/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<style>
	body {background-color: hsla(120,100%,50%,0.3);}
	</style>
</head>
			<%= form_tag accounts_path,:method => 'get' do %>
				<p>
					<%= text_field_tag :search,params[:search] %>
					<%= submit_tag :Search %>
					<%= link_to 'clear',params.clear %>
				</p>			
			<% end %>
			<h2>List Of Accounts created</h2>
	<table border="1" cellspacing="0" cellpadding="2">
		<thead>
				<tr>
					<th>Name</th>
					<th>Description</th>
					<th>Place</th>
					<th>Registration Number</th>
					<th>User Name</th>
					<th>Update</th>
					<th>Delete</th>
				</tr>
		</thead>
<body>
		<tbody>
			<% for account in @accounts %>
				<tr>

					<td><%= account.name %></td>
					<td><%= account.description %></td>
					<td><%= account.place %></td>
					<td><%= account.registration_number %></td>
					<td><%= account.user_name %></td>
					<td><%= link_to 'Edit',edit_account_path(account) %></td>
					<td><%= link_to 'Delete',account_path(account),
						method: :delete,data: {confirm: 'Are you sure?'} %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</body>
<strong>Click here to </strong><%= link_to 'Create new account',new_account_path(account) %><br>
<strong>Click here to </strong><%= link_to 'list of users',user_list_account_path(account) %><br>
</html>
<strong><%= link_to 'Sign In',new_admin_session_path(account) %>
  

app/views/accounts/new.html.erb
<!DOCTYPE html>
<html>
	<head>
		<style>
			 body { background-color: hsla(120,100%,75%,0.3);background-position: right top;
				 	font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
				    width: 100%;
			 		
					
				 
				  }
			 h2 {colour: orange;}
				 
		</style>
	</head>
	<body>
		<h2>Register the details</h2>
		<%= form_for @account do |f|%>
		    <% if @account.errors.any? %>
				<div id= "Error_messages">
					<ol>
						<%= pluralize(@account.errors.count,"error") %> prohibited this from being saved:
						
							<% for error in @account.errors.full_messages %>
								<li><%= error %></li>
							<%	end %>
					</ol>
				</div>
			<% end %>

				<div class= "input-box">
					<%= f.label :name %>
					<%= f.text_field :name %>
				</div>

				<div class= "input-box">
					<%= f.label :description %>
					<%= f.text_area :description %>
				</div>

				<div class= "input-box">
					<%= f.label :place %>
					<%= f.text_field :place %>
				</div>

				<div class= "input-box">
					<%= f.label :registration_number %>
					<%= f.text_field :registration_number %>
				</div>

				<div class= "input-box">
					<%= f.label :user_name %>
					<%= f.text_field :user_name %>
				</div>					

				<span style = "width:100px; float:left;" >&nbsp;</span>
					<%= f.submit %>
			
		<% end %><br>
	</body>
<%= link_to 'List of accounts',accounts_path(@account) %>
</html>

app/views/accounts/show.html.erb
<html>

	<style>
		body { background-color: #F0F8FF; 
				font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
			    width: 100%;
			    border-collapse: collapse;}
		th {background-color: #A7C942;
    		color: #ffffff;}	    


	</style>

	<h2><strong>Details of <%= @account.name%></strong></h2>
	<table bgcolor="#F0F8FF" border="2" cellpadding="2" cellspacing="0">
		<thead>
			<tr>
				<th>Content</th>
				<th>Details</th>
			</tr>			
			<tr>
				<td>Name</td>
				<td><%= @account.name%></td>
			</tr>
			
			<tr>	
				<td>Description</td>
				<td><%= @account.description%></td>
			</tr>

			<tr>	
				<td>Place</td>
				<td><%= @account.place%></td>
			</tr>
			
			<tr>	
				<td>Registration Number</td>
				<td><%= @account.registration_number%></td>
			</tr>
			
			<tr>	
				<td>User Name</td>
				<td><%= @account.user_name%></td>
			</tr>
			
			<tr>	
				<td>Total Income</td>
				<td><%= @total_income%></td>
			</tr>	

			<tr>
				<td>Total Expense</td>
				<td><%= @total_expense%></td>
			</tr>
			

				
			<tr>
					<strong><td> Balance </td></strong>
					<td><%=@balance%></td>
			</tr>
				
		</thead>
		
		
	</table><br>
</html>


				<strong>Click here to </strong><td><%= link_to 'edit',edit_account_path(@account)%></td><br>
				<strong>Click here to </strong><td><%= link_to 'delete',account_path(@account),
						method: :delete,data: {confirm: 'Are you sure?'} %></td>


						s

app/views/accounts/user_list.html.erb
<!DOCTYPE html>

<html>
<head>
	<style>
	body {background-color: hsla(120,100%,50%,0.3);}
	table {border-style: solid;}
	</style>
</head>
			<h2>List of users</h2>
	<table border="1" cellspacing="0" cellpadding="2">
		<thead>
			<tr>
				<th>First Name</th>
				<th>Last Name</th>
				<th>Place</th>
			</tr>
		</thead>
<body>
		<tbody>
			<% for user in @users %>
			<tr>

				<td><%= user.firstname %></td>
				<td><%= user.lastname %></td>
				<td><%= user.place %></td>
			</tr>
			<% end %>
		</tbody>
	</table>

</html>